version: '3'
services:
#  client:
#    build:
#    context: .
#    name: client-node
#    dockerfile: client/Dockerfile.dev
#  server:
#    build:
#    context: .
#    name: server-node
#    dockerfile: server/Dockerfile.dev
#  worker:
#    build:
#    context: .
#    name: worker-node
#    dockerfile: worker/Dockerfile.dev
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
  redis:
    image: 'redis:latest'
    restart: always
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres123
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx-proxy:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '80:80'
    command: [nginx-debug, '-g', 'daemon off;']
